export * from  './loginPage.view'
export * from  './inventoryPage.view'
export * from  './itemPage.view'
export * from  './cartPage.view'
export * from './checkoutStepOnePage.view'
export * from './checkoutStepTwoPage.view'
export * from './checkoutCompletePage.view'